/* src: 2015-11-28 02:58:59 */
/* gen: 2015-12-01 10:59:15 */
(function(){function B(){return function(){}}function u(){}function ea(a){return parseFloat(a)}function h(a){return parseInt(a,10)}function z(a,b){if(l(b)){var c;c=Math.pow(10,b);return Math.round(a*c)/c}return Math.round(a)}function fa(a){return Math.ceil(a)}function bb(a){return Math.floor(a)}function ga(){return 100*((new Date).getTime()%1E7)+z(99*Math.random())}function l(a){return"undefined"!=typeof a}function D(a,b){return l(a)?a:b||!1}function T(a){return l(a)?h(a):!1}function Z(a,b){return b?n.getElementsByTagName(a):n.getElementsByTagName(a)[0]}
function Da(a){return a.getAttribute("baseStyleRight")}function Ea(a,b,c){a.setAttribute(b,c+"")}function ha(a,b){for(var c in a)a.hasOwnProperty(c)&&b.call(a[c],c,a[c])}function E(a,b){b||(b=B());var c=t("script");c.setAttribute(Fa,ia);c.setAttribute("src",a);c.setAttribute("async","async");l(c)&&(L?c.onreadystatechange=function(){"loaded"!=this.readyState&&"complete"!=this.readyState||setTimeout(b,0)}:c.onload=function(){setTimeout(b,0)},ja.appendChild(c))}function ka(a){var b=t("style");b.setAttribute("rel",
"stylesheet");b.setAttribute(Fa,"text/css");ja.appendChild(b);L?b.styleSheet.cssText=a:b.appendChild(n.createTextNode(a))}function la(a,b,c){if(a.length)for(var d=a.length;d--;)a[d].style[b]=c}function cb(){var a=!1,b=navigator,c=null;if(l(b.plugins)&&"object"==typeof b.plugins["Shockwave Flash"])!(c=b.plugins["Shockwave Flash"].description)||l(b.mimeTypes)&&b.mimeTypes["application/x-shockwave-flash"]&&!b.mimeTypes["application/x-shockwave-flash"].enabledPlugin||(c=c.replace(/^.*\s+(\S+\s+\S+$)/,
"$1"),a=[0,0,0],a[0]=h(c.replace(/^(.*)\..*$/,"$1")),a[1]=h(c.replace(/^.*\.(.*)\s.*$/,"$1")),a[2]=/[a-zA-Z]/.test(c)?h(c.replace(/^.*[a-zA-Z]+(.*)$/,"$1")):0);else if(l(f.ActiveXObject))try{var d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");d&&(c=d.GetVariable("$version"))&&(c=c.split(" ")[1].split(","),a=[h(c[0]),h(c[1]),h(c[2])])}catch(e){}return a=!1!==a?a.join("."):a}function Lb(){var a=cb(),b=["10","0","42"];if(!1===a)return!1;a=a.split(".");b[0]=parseInt(b[0],10);b[1]=parseInt(b[1],10)||
0;b[2]=parseInt(b[2],10)||0;return a[0]>b[0]||a[0]==b[0]&&a[1]>b[1]||a[0]==b[0]&&a[1]==b[1]&&a[2]>=b[2]?a.join("."):!1}function s(a,b,c){if(a){"[object NodeList]"!=Object.prototype.toString.call(a)&&(a=[a]);b=b.split(" ");var d=b.length,e;for(e=0;e<d;e++)ha(a,function(){this.addEventListener?this.addEventListener(b[e],c,!1):this.attachEvent("on"+b[e],c)})}}function Ga(a,b,c){if(a){"[object NodeList]"!=Object.prototype.toString.call(a)&&(a=[a]);b=b.split(" ");var d=b.length,e;for(e=0;e<d;e++)ha(a,
function(){this.detachEvent?this.detachEvent("on"+b[e],c):(this.removeEventListener(b[e],c,!0),this.removeEventListener(b[e],c))})}}function $(a,b){b=b.split(" ");for(var c=0;c<b.length;c++)a.className=a.className.replace(RegExp("\\b"+b[c]+"\\b","g"),"").replace(/\s+/g," ").replace(/(^ | $)/g,"")}function v(a,b){$(a,b);b=b.split(" ");for(var c=0;c<b.length;c++)a.className+=" "+b[c];a.className=a.className.trim()}function Ha(a,b){return RegExp("\\b"+b+"\\b","im").test(a.className)}function db(a,b){a.innerHTML=
b;for(var c=[],d=a.childNodes,e=0;d[e];e++)!d[e].nodeName||"script"!==d[e].nodeName.toLocaleLowerCase()||d[e].type&&d[e].type.toLowerCase()!==ia||c.push(d[e]);for(var g in c){var d=c[g].parentNode?c[g].parentNode.removeChild(c[g]):c[g],e=a||ja,k=t("script");k.type=ia;l(d.src)&&d.src?k.src=d.src:k.appendChild(n.createTextNode(d.text||d.textContent||d.innerHTML||""));e.appendChild(k)}}function t(a){return n.createElement(a)}function ma(){var a="",a="?rt="+ga();n.referrer&&(a+="&r="+encodeURIComponent(n.referrer));
U&&(a+="&recurring=1");eb&&(a+="&flash="+encodeURIComponent(eb));L&&(a+="&isie=1");"https:"==window.location.protocol&&(a+="&https=1");Ia&&(a+="&md="+encodeURIComponent(Ia));a+="&f="+na;l(screen.width)&&(a+="&scr="+escape(screen.width+"x"+screen.height));var b;if(null===V){b=t("div");b.setAttribute("style","width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -10000px !important; ");b.setAttribute("class","pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links");
x.appendChild(b);V=!1;if(null!==x.getAttribute("abp")||null===b.offsetParent||0==b.offsetHeight||0==b.offsetLeft||0==b.offsetTop||0==b.offsetWidth||0==b.clientHeight||0==b.clientWidth)V=!0;if(!V){var c=G(b);if("none"==c.getPropertyValue("display")||"hidden"==c.getPropertyValue("visibility"))V=!0}x.removeChild(b)}b=V;b&&(a+="&bl=1");w&&(a+="&lm=1");if(l(f[aa].multishows_params)){b=f[aa].multishows_params;for(var d in b)b.hasOwnProperty(d)&&(a+="&"+encodeURIComponent(d)+"="+encodeURIComponent(b[d]))}return a+=
f[q].multishowsAdd?"&"+f[q].multishowsAdd:""}function Mb(a,b){return function(){if(b&&""!=b.innerHTML){var c=b.getClientRects()[0];E(H+oa+"/area_size/?data="+a+","+z(c.right-c.left)+","+z(c.bottom-c.top))}}}function Ja(a){var b=a.which?a.which:a.button;a=(L?a.srcElement:a.target).nodeName.toLowerCase();"a"!=a&&"img"!=a||2==b||3==b||(clearTimeout(Ka),Ka=setTimeout(function(){Ka=null;La()},500))}function Nb(){var a="";if(pa)for(var b in m)m.hasOwnProperty(b)&&"object"==typeof m[b]&&(a+=escape(b.substr(1))+
";");0<a.length&&(a=a.substring(0,a.length-1));return a}function fb(a){gb(a.target?a.target:a.srcElement)}function Ob(a){var b=/\/(i)\/(a??)(\d+?)\//m,c=b.exec(a);null==c&&(b=/\/(ii)\/(a??)(\d+?)\//m,c=b.exec(a));var d=!1,e=!1;null!=c&&16!=c[3]&&(d=h(c[3]),d=(2*(10*d+40)-40)/10,16<=d&&(d=16),e=10*d+40,d=a.replace(b,"/$1/$2"+d+"/"));return{url:d,size:e}}function hb(a){var b=h("CSS1Compat"!=n.compatMode||f.opera?x.scrollTop:I.scrollTop),c=h(b+Ma()),d=h("CSS1Compat"!=n.compatMode||f.opera?x.scrollLeft:
I.scrollLeft),e=h(d+(ba&&!f.opera?I.clientWidth:x.clientWidth)),g=a.getClientRects()[0],k=z(g.top)+b,P=z(g.bottom)+b,l=z(g.left)+d,g=z(g.right)+d;k<b&&(a.style.top=h(a.style.top)+(b-k)+qa+p);P>c&&(a.style.top=h(a.style.top)-(P-c)-qa+p);l<d&&(a.style.left=h(a.style.left)+(d-l)+qa+p);g>e&&(a.style.left=h(a.style.left)-(g-e)-qa+p)}function ib(a){for(var b=0,c=0;a&&"relative"!=G(a).position&&G(a).position!=Na;)b+=h(a.offsetTop),c+=h(a.offsetLeft),a=a.offsetParent;return{top:b,left:c}}function G(a){return a.$=
a.$||a.currentStyle||getComputedStyle(a,0)}function gb(a){var b,c=ib(a),d=Ob(a.src),e=d.size;if((d=d.url)&&d!=a.src){a.previousSibling&&"img"==a.previousSibling.nodeName.toLowerCase()?b=a.previousSibling:(b=a.cloneNode(!1),L&&b.detachEvent("onmouseover",fb),b.style.position=Na,b.style.top=ra,b.style.left=ra,b.style.margin=0+p,b.style.maxWidth="",b.style.maxHeight="",s(b,"mouseout",function(){clearTimeout(~~b.getAttribute(sa));Ea(b,Oa,setTimeout(function(){jb(b,a)},ta))}),a.parentNode.insertBefore(b,
a));if(b.src==a.src){var g=b.cloneNode(!1);s(g,"load",function(){b.src=g.src;setTimeout(function(){g.parentNode.removeChild(g)},100)});g.src=d;b.parentNode.insertBefore(g,b)}b.width=a.width;b.height=a.height;b.style.top=c.top+p;b.style.left=c.left+p;a.style.visibility="hidden";a.parentNode.style.zIndex=1E5;hb(b);b.setAttribute(sa,setTimeout(function(){kb(b,e)},ta))}}function jb(a,b){clearTimeout(~~a.getAttribute(sa));var c=ib(b),d=h(a.height)-F;a.width=h(a.width)-F;a.height=d;d=h(c.left)>h(a.style.left)?
h(a.style.left)+F/2:h(a.style.left)-F/2;a.style.top=(h(c.top)>h(a.style.top)?h(a.style.top)+F/2:h(a.style.top)-F/2)+p;a.style.left=d+p;h(a.width)>h(b.width)?a.setAttribute(Oa,setTimeout(function(){jb(a,b)},ta)):(a.style.top=ra,a.style.left=ra,b.style.visibility="",b.parentNode.style.zIndex="")}function kb(a,b){clearTimeout(~~a.getAttribute(Oa));var c=h(a.height)+F;a.width=h(a.width)+F;a.height=c;c=h(a.style.left)-F/2;a.style.top=h(a.style.top)-F/2+p;a.style.left=c+p;hb(a);h(a.width)<b&&a.setAttribute(sa,
setTimeout(function(){kb(a,b)},ta))}function lb(a){a=u("lx_block_params",a);var b=a.length,c=[];if(b)for(var d=0;d<b;d++)for(var e=a[d].attributes,g=e.length,k;g--;)k=e[g],0===k.name.indexOf("data-")&&(c[k.name.replace("data-","")]=k.value);return c}function La(a){if(!ua){ua=!0;var b=Nb();b&&(a?(n.write('<script type="'+ia+'" language="JavaScript" src="'+H+ca+b+"/"+ma()+'">\x3c/script>'),ua=!1):E(H+ca+b+"/"+ma(),function(){ua=!1}))}}var m={
"_578431":{id:"lx_578431",type:"js_npm"},"_578448":{id:"lx_578448",type:"js_npm"},"_578454":{id:"lx_578454",type:"js_npm"},"_578453":{id:"lx_578453",type:"js_npm"},"_575295":{id:"lx_575295",type:"js_npm"}
},n=document,f=window,x=n.body,I=n.documentElement,ja=function(){var a=Z("head");if(a)return a;for(a=I.firstChild;a&&"#text"==a.nodeName.toLowerCase();)a=a.nextSibling;if(a&&"#text"!=a.nodeName.toLowerCase())return a;
a=t("head");I.appendChild(a);return a}(),mb=h(195481),q="__lxG"+mb+"__",aa="__lxG__",va={},M=navigator.userAgent.toLowerCase(),Pb=(navigator.userAgent.toLowerCase().match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[])[1],ba="CSS1Compat"===n.compatMode,wa=/chrome/.test(M),xa=/opera/.test(M),L=/msie/.test(M)&&!xa,Qb=!window.ActiveXObject&&"ActiveXObject"in window,U=!1,ua=!1,Ka=null,pa=0,Q=[],W=null,eb=wa?Lb():cb(),p="px",ra="-100000"+p,Na="absolute",r={},ia="text/javascript",Fa="type",A="",nb=!1,qa=3,F=10,
ta=10,Oa="shrTmr",sa="enlrgTmr",ya=L&&(!ba||8>h(Pb)&&ba),oa="luxadv.com",H="http"+("https:"==window.location.protocol?"s":"")+"://",ca=oa+"/multishows/",ob=H+oa+"/real_show_log/?data=",y={},pb=!1,za=!1,Aa=!1,R=!1,Pa=1,qb=1,rb=1,Qa=0,Ra=0,Sa=!1,Ba=-1,Ia=!1,Ta="__lx"+mb,Ua=Ta+"_load_cnt",sb=Ta+"_load_tmr",tb=Ta+"_load_tmr_pre",w=!1;if(!w)var Rb=function(a,b,c,d){a.innerHTML="";c=c||100;d=d||100;var e=t("iframe");e.id=a.id+"_frame";e.K="allow-same-origin allow-scripts allow-popups allow-forms";
e.style.width=c+p;e.style.height=d+p;e.setAttribute("allowtransparency","true");e.setAttribute("marginwidth","0");e.setAttribute("marginheight","0");e.setAttribute("hspace","0");e.setAttribute("vspace","0");e.setAttribute("frameborder","0");e.setAttribute("scrolling","no");e.src=encodeURI("javascript:'"+Va(b)+"'");a.appendChild(e)},Va=function(a){return(a+"").replace(/[\\"']/g,"\\$&").replace(/\u0000/g,"\\0")};var V=null;if(!w)var X=[],Sb=function(a,b,c){var d=b||1;if(X.length){for(var e in X.aa)X.aa.hasOwnProperty(e)&&
Ga(f,"resize orientationchange",X[e]);X=[]}c.min=c.min||Number.NEGATIVE_INFINITY;c.max=c.max||Number.POSITIVE_INFINITY;ha(a,function(){function a(){var e=Math.round(Math.max(Math.min(ea(G(b).width)/(10*d),parseFloat(c.max)),parseFloat(c.min)));b.style.fontSize=e+p}var b=this;a();X.push(a);s(f,"resize orientationchange",a)})},Tb=function(a,b){function c(b){var c=a,d=G(c)["line-height"],d="normal"==d?1.2*ea(G(c)["font-size"]):/[a-z]+/im.test(d)?parseFloat(d):ea(G(c)["font-size"])*parseFloat(d);return Math.ceil(d*
b)}function d(b){var c=b.lastChild&&!b.lastChild.nodeValue&&b.lastChild.innerHTML?b.lastChild.innerHTML:b.lastChild.nodeValue;if(b.lastChild.children&&0<b.lastChild.children.length)return d(Array.prototype.slice.call(b.children).pop());if(b.lastChild&&c&&""!=c&&c!=k.n)return b.lastChild;b.lastChild.parentNode.removeChild(b.lastChild);return d(a)}function e(b,c){if(c&&b){var f=Boolean(!b.nodeValue&&b.innerHTML),h=(f?b.innerHTML:b.nodeValue).replace(k.n,"");p||(n=0<m.length?m.shift():"",p=h.split(n));
1<p.length?(q=p.pop(),g(b,p.join(n),f)):p=null;if(p){if(a.clientHeight<=c)if(0<=m.length&&""!=n)g(b,p.join(n)+n+q,f),p=null;else return a.innerHTML}else""==n&&(g(b,"",f),b=d(a),m=k.M.slice(0),n=m[0],q=p=null);return e(b,c)}}function g(a,b,c){c?a.innerHTML=b+k.n:a.nodeValue=b+k.n}b=b||{};var k={R:b.clamp||2,C:"undefined"!=typeof b.C?b.C:!0,M:[".","-","\u2013","\u2014"," "],n:"\u2026"},f=a.style,l="undefined"!=typeof a.style.webkitLineClamp,h=k.R,m=k.M.slice(0),n=m[0],p,q;l&&k.C?(f.overflow="hidden",
f.textOverflow="ellipsis",f.webkitBoxOrient="vertical",f.display="-webkit-box",f.webkitLineClamp=h):(f=c(h),f<=a.clientHeight&&e(d(a),f))};var C={get:function(a,b){var c;this.s(a)?(c=n.cookie.replace(RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"),c=decodeURIComponent(c)||(l(b)?b:null)):c=l(b)?b:null;return c},set:function(a,b,c,d,e,g){if(!a||/^(?:expires|max\-age|path|domain|secure)$/i.test(a))return!1;var f="";if(c)switch(c.constructor){case Number:f=
Infinity===c?"; expires=Fri, 31 Dec 9999 23:59:59 GMT":"; max-age="+c;break;case String:f="; expires="+c;break;case Date:f="; expires="+c.toUTCString()}n.cookie=encodeURIComponent(a)+"="+encodeURIComponent(b)+f+(e?"; domain="+e:"")+(d?"; path="+d:"")+(g?"; secure":"");return!0},ha:function(a,b,c){if(!a||!this.ia(a))return!1;n.cookie=encodeURIComponent(a)+"=; expires=Thu, 01 Jan 1970 00:00:00 GMT"+(c?"; domain="+c:"")+(b?"; path="+b:"");return!0},s:function(a){return RegExp("(?:^|;\\s*)"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,
"\\$&")+"\\s*\\=").test(n.cookie)},list:function(){for(var a=n.cookie.replace(/((?:^|\s*;)[^\=]+)(?=;|$)|^\s*|\s*(?:\=[^;]*)?(?:\1|$)/g,"").split(/\s*(?:\=[^;]*)?;\s*/),b=0;b<a.length;b++)a[b]=decodeURIComponent(a[b]);return a}};if(!w)var Ma=function(){return ba&&!f.opera?I.clientHeight:x.clientHeight};u=n.getElementsByClassName?function(a,b){return(b||document).getElementsByClassName(a)}:function(a,b){b=b||document;var c=b.getElementsByTagName("*"),d=c.length,e=a.split(/\s+/),g=e.length,f=[],h,l;
for(h=0;h<d;h++)for(l=0;l<g;l++)if(~c[h].className.search("\\b"+e[l]+"\\b")){f.push(c[h]);break}return f};if(!w){var ub=function(a){if(0===a.offsetWidth||0===a.offsetHeight)return!1;for(var b=Ma(),c=ba&&!f.opera?I.clientWidth:x.clientWidth,d=a.getClientRects(),e=0,g=d.length;e<g;e++){var k=d[e],h=k.height?k.height:k.bottom-k.top,l=k.width?k.width:k.right-k.left,l=0<=k.left+0.25*l&&k.left+0.75*l<c;if(h=0<=k.top+0.25*h&&k.top+0.75*h<b)if(h=l){k=n.elementFromPoint((k.left+k.right)/2,(k.top+k.bottom)/
2);if(k===a)k=!0;else a:{if(k)for(k=k.parentNode;null!=k;){if(k==a){k=!0;break a}k=k.parentNode}k=!1}h=k}if(h)return!0}return!1},Ub=function(){W&&(clearTimeout(W),W=null);for(var a=Q.length,b=0;b<a;b++)if(Q[b]){var c=Q[b][1];ub(Q[b][0])&&(delete Q[b],E(ob+encodeURIComponent(c),B()))}},vb=function(){W&&clearTimeout(W);W=setTimeout(Ub,500)};s(f,"scroll",vb)}if(!w){va[q]={};va[q].L=function(a){if(!A)return!0;a=a||f.event;var b=(a.target||a.srcElement).nodeName.toLowerCase();if(L&&"a"==b)return!0;A+=
"?rnd="+ga()+(f[q].popunderAdd?"&"+f[q].popunderAdd:"");xa?(f.open(A,q+"popunder","resizable=1,toolbar=1,location=1,menubar=1,status=1,directories=0,width="+screen.availWidth+",height="+screen.availHeight),f.blur(),f.focus()):wa?Vb(A,a):L?wb(A):Qb?Wb(A):setTimeout(function(){wb(A)},0);Ga(x,wa||xa?"mousedown":"click",va[q].L);return!0};var wb=function(a){var b=f.open("about:blank",q+"popunder","resizable=1,toolbar=0,location=1,menubar=1,directories=0,width="+f.screen.availWidth+",height="+f.screen.availHeight+
",scrollbars=1");b&&(b.blur(),b.P=function(c){with(c)Params=c.fa,Main=function(){l(window.mozPaintCount)&&window.open("about:blank").close();try{opener.window.focus()}catch(c){}b.location=a},Main()},b.P(b),b.blur())},Wb=function(a){var b=f.open("about:blank",q+"popunder","toolbar=0,scrollbars=1,location=1,statusbar=1,menubar=0,resizable=1,top=0,left=0,width="+f.screen.availWidth+",height="+f.screen.availHeight+"");if(b){b.blur();try{b.opener.focus()}catch(c){}b.location=a}},Vb=function(a,b){b=b||
f.event;var c=b.target,d=t("A");d.id="FakeLink";x.appendChild(d);var e=n.createEvent("MouseEvents");e.initMouseEvent("click",c?!0:!1,!0,f,1,!1,!1,!1,!1,!0,!1,!1,!1,!1,null);d.href=a;d.target="_blank";d.dispatchEvent(e)}}l(f[q])||(f[q]={});l(f[q].evil)||(f[q].evil=db);l(f[q].instances)||(f[q].instances=[]);l(f[q].blocks)||(f[q].blocks=[]);var Wa=ga(),na=q+Wa;f[na]={};f[q].instances.push(Wa);l(f[aa])||(f[aa]={});l(f[q].closed)||(f[q].closed=B(),f[q].clicked=B());l(f[q].popunderShow)||(f[q].popunderShow=
!1);l(f[q].allLoaded)||(f[q].allLoaded=B());l(f[q].popunderAdd)||(f[q].popunderAdd="");l(f[q].multishowsAdd)||(f[q].multishowsAdd="");f[na].parser=f[q].parser=function(a){Q=[];for(var b in a)if(a.hasOwnProperty(b)){var c=a[b];if("cfg"!=c.type)if("counters"==c.type){if(c.hasOwnProperty("urls"))for(var d=0;d<c.urls.length;d++)t("img").src=c.urls[d]}else if("iframe_counters"==c.type){if(c.hasOwnProperty("sources"))for(d=0;d<c.sources.length;d++){var e=c.sources[d],g=t("iframe");g.id=aa+"frame_tracker_"+
d;g.K="allow-same-origin allow-scripts allow-forms";g.style.width=1+p;g.style.height=1+p;g.setAttribute("allowtransparency","true");g.setAttribute("marginwidth","0");g.setAttribute("marginheight","0");g.setAttribute("hspace","0");g.setAttribute("vspace","0");g.setAttribute("frameborder","0");g.setAttribute("scrolling","no");g.src="javascript:'"+Va(e)+"'";x.appendChild(g)}}else if("get_area_size"==c.type){if(c.hasOwnProperty("ids"))for(e=0;e<c.ids.length;e++)d=c.ids[e],setTimeout(Mb(d,n.getElementById(m["_"+
d].id)),3E3)}else{if("mdcheck"==c.type)return c.hasOwnProperty("url")&&E(H+c.url+(~c.url.indexOf("?")?"&":"?")+"f="+na),!0;if("mdparam"==c.type)return c.hasOwnProperty("param")&&(Ia=c.param,c.hasOwnProperty("alg")&&c.alg&&(ca=c.alg+"."+oa+"/multishows/"),setTimeout(function(){La(0)},0)),!0;if(l(m["_"+c.id])&&l(c.source)){if((e=n.getElementById(m["_"+c.id].id))&&"html"==c.type&&c.source){U||(ka(c.style),s(e,"click",Ja));e.innerHTML=c.source;m["_"+c.id].i=!0;g=lb(e);m["_"+c.id].ga=g;l(c.real_show_log)&&
c.real_show_log&&Q.push([e,c.real_show_log]);if(!w&&D(g.lxm_responsive)){var k=e.querySelectorAll(".lx_anons"),d=0,d=function(a,b){return function(){Sb(a,D(b.lxm_fit_factor,1.5),{min:D(b.lxm_fit_min,14)+p,max:D(b.lxm_fit_max,20)+p});ha(a,function(a,c){Tb(c,{clamp:D(b.lxm_clamp)})})}}(k,g);setTimeout(d,50);setTimeout(d,250);setTimeout(d,500);setTimeout(d,1E3);setTimeout(d,2E3)}if(l(m["_"+c.id].zoomImages)&&m["_"+c.id].zoomImages)for(d=e.getElementsByTagName("img"),g=d.length,k=0;k<g;k++)n.addEventListener?
d[k].addEventListener("mouseover",function(){gb(this)},!1):d[k].attachEvent("onmouseover",fb)}w||!e||"pu"!=c.type||nb||(A=c.hasOwnProperty("url")?c.url:H+"s.luxadv.com//pu/"+c.id+".html",c.hasOwnProperty("pattern")&&c.hasOwnProperty("timeout")?(d=C.get(sb,0),(new Date).getTime()-d>6E4*c.timeout&&xb(1),d=h(C.get(Ua,0)),~c.pattern.indexOf(d)||~c.pattern.indexOf(7)&&7<=d||(A=!1)):A=!1,A&&(s(x,wa||xa?"mousedown":"click",va[q].L),m["_"+c.id].i=!0),nb=!0);"js"==c.type&&(!e&&"js_npm"==D(m["_"+c.id].type,
!1)&&D(m["_"+c.id].location,!1)&&(d=n.querySelector(m["_"+c.id].location))&&(e=t("div"),e.id=m["_"+c.id].id,d.parentNode.insertBefore(e,d.nextSibling)),e&&(U||(l(c.style)&&ka(c.style),s(e,"click",Ja)),db(e,c.source),m["_"+c.id].i=!0));!w&&e&&"iframe"==c.type&&(Rb(e,c.source,c.width,c.height),m["_"+c.id].i=!0);!w&&e&&"float"==c.type&&(g=!1,U||(ka(c.style),s(e,"click",Ja)),d=c.id,l(r[d])||(r[d]=m["_"+d],r[d].l=d,r[d].a=e,r[d].f=!1,r[d].j=!1,r[d].m=!1,r[d].c=0,r[d].e=!1,r[d].w=!1,r[d].A=!1,r[d].k=!1,
l(c.real_show_log)&&c.real_show_log&&(r[d].w=!0,r[d].A=c.real_show_log),g=!0),r[d].a.innerHTML=c.source,r[d].a.style[r[d].side]=-1E3+p,r[d].a.style.display="block",r[d].width=h(r[d].a.width?r[d].a.width:r[d].a.offsetWidth),r[d].a.style[r[d].side]=-r[d].width+p,Xb(r[d],g),r[d].e&&(r[d].e=!1),yb(r[d])(),m["_"+c.id].i=!0);!w&&e&&"mobile"==c.type&&(g=!1,U||ka(c.style),d=c.id,!1===R&&(R=l(c.isTablet)?h(c.isTablet):0),l(y[d])||(y[d]=m["_"+d],y[d].l=d,y[d].a=e,y[d].j=!1,y[d].c=0,y[d].e=!1,g=!0),e.innerHTML=
c.source,m["_"+c.id].i=!0,Yb(y[d],g),y[d].e&&(y[d].e=!1));c.hasOwnProperty("iframe_source")&&(g=t("iframe"),g.id=c.id+"_pixel_frame",g.K="allow-same-origin allow-scripts allow-forms",g.style.width=1+p,g.style.height=1+p,g.setAttribute("allowtransparency","true"),g.setAttribute("marginwidth","0"),g.setAttribute("marginheight","0"),g.setAttribute("hspace","0"),g.setAttribute("vspace","0"),g.setAttribute("frameborder","0"),g.setAttribute("scrolling","no"),g.src="javascript:'"+Va(c.iframe_source)+"'",
e.appendChild(g));w||"inlinevideo"!=c.type||(e=m["_"+c.id],Zb(n.querySelector(e.location),{da:c.video_url,D:c.click_url,ca:c.video_start_url,N:c.video_end_url,ea:c.width,ba:c.height,J:D(c.overlay_html,""),F:D(c.full_view_percent,100),q:e.width,Q:e.style,S:e.hideClose,T:e.hideMarker,G:e.hidePostblock}))}}}for(var P in m)m.hasOwnProperty(P)&&!l(m[P].i)&&l(m[P].cap)&&m[P].cap();U=!1;setTimeout(function(){f[q].allLoaded()},0);w||vb()};if(!w)var Xb=function(a,b){b&&(s(n,"scroll",yb(a)),ya&&(Ca(a)(),s(f,
"resize",zb(a)),s(f,"scroll",zb(a))));for(var c=u("close",a.a),d=c.length,e=0;e<d;e++)s(c[e],"click",$b(a));c=u("ref",a.a);d=c.length;for(e=0;e<d;e++)s(c[e],"click",Ab(a))},$b=function(a){return function(b){if(b||f.event)b=b||f.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;a.j=!0;Xa(a);b=new Date;b.setTime(b.getTime()+1000*60*480);C.set("_lxretpopupignore",1,b,"/")}},Ab=function(a){return function(b){if(b||f.event)b=b||f.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;
clearTimeout(a.c);a.e=!0;Xa(a,function(){E(H+ca+a.l+"/"+ma(),B())})}},yb=function(a){return function(){if(!a.j&&!a.e){var b=h(I.scrollTop?I.scrollTop:x.scrollTop);!a.f&&b>=a.limit?ac(a):a.f&&b<a.limit&&Xa(a)}}},Ca=function(a){return function(){a.a[a.side+"Offset"]=h(a.a.style[a.side]);var b={bottom:!0};"left"==a.side&&(b.left=!0);"right"==a.side&&(b.right=!0);pinBlock(a.a,b)}},zb=function(a){return function(){l(a.H)&&clearTimeout(a.H);a.H=setTimeout(Ca(a),100)}},Bb=function(a){var b=0;return b=ya?
a.a[a.side+"Offset"]:h(a.a.style[a.side])},ac=function(a){a.f=!0;l(a.g)&&clearInterval(a.g);clearTimeout(a.c);a.c=setTimeout(Ab(a),1E3*a.refresh);a.a.style.display="block";a.g=setInterval(function(){var b=Bb(a),c=b+22;0>b&&0>c?(a.m=!0,a.a.style[a.side]=c+p):(clearInterval(a.g),a.m=!1,a.a.style[a.side]=0+p,a.w&&(a.k=setTimeout(bc(a),1E3)));ya&&Ca(a)()},15)},bc=function(a){return function(){a.k&&clearTimeout(a.k);a.w=!1;a.A&&E(ob+encodeURIComponent(a.A),B())}},Xa=function(a,b){a.f=!1;l(a.g)&&clearInterval(a.g);
clearTimeout(a.c);a.k&&clearTimeout(a.k);a.g=setInterval(function(){var c=Bb(a),d=c-22;c>=-a.width&&d>-a.width?(a.m=!0,a.a.style[a.side]=d+p):(clearInterval(a.g),a.m=!1,a.a.style[a.side]=-a.width+p,a.a.style.display="none",l(b)&&b());ya&&Ca(a)()},15)};if(!w)var Cb=function(){for(var a=!1,b=Z("meta",!0),c=b.length;c--;)if(l(b[c].name)&&"viewport"==b[c].name){a=b[c];break}return a},Ya=!1,cc=function(){var a=Cb();a&&(Ya=a.getAttribute("content"));a?Ea(a,"content","width=device-width"):(n.getElementsByTagName("head").length||
n.insertBefore(t("head"),n.getElementsByTagName("body")[0]),a=t("meta"),a.name="viewport",a.content="width=device-width",Z("head").appendChild(a))},Yb=function(a,b){var c=lb(a.a);if(b){for(var d in c)c.hasOwnProperty(d)&&h(c[d])&&"lxm_"==d.substring(0,4)&&v(a.a,d);v(a.a,"lxm_os_"+N());J()&&v(a.a,"lxm_meta_set");l(f.devicePixelRatio)&&v(a.a,"lxm_pixel_ratio_"+Math.ceil(f.devicePixelRatio))}for(var e=u("lxm_js_block_close",a.a),g=e.length;g--;)s(e[g],"click",dc(a));a.I=!1;a.v=!1;if(T(c.lxm_fullscreen)){a.v=
!0;cc();e=u("lxm_sl_trigger",a.a);for(g=e.length;g--;)s(e[g],"click",ec(a,e[g]));var k=u("lxm_sl",a.a)[0],c=u("lxm_button_close",k)[0];s(c,"click",function(){return function(){k.style.display="none"}}());l(screen.width)&&(c="lxm_scr_"+250*fa(Math.max(screen.width,screen.height)/250),v(a.a,c));c=Math.max(n.documentElement.clientWidth,f.innerWidth||0);e=Math.max(n.documentElement.clientHeight,f.innerHeight||0);v(a.a,"lxm_scr_width_"+100*fa(c/100));v(a.a,"lxm_scr_height_"+100*fa(e/100));Db(a.a,"minscale",
Eb("minimum-scale"));Db(a.a,"initscale",Eb("initial-scale"));c="lxm_zoom_"+(0.25*Math.ceil(n.documentElement.clientWidth/f.innerWidth/0.25)).toString().replace(".","_");v(a.a,c);c=u("lx_hide_logo",a.a);for(e=c.length;e--;)s(c[e],"click",fc(a));c=gc(a);e=["orientationchange","touchmove","touchend","scroll","resize"];for(d in e)e.hasOwnProperty(d)&&s(f,e[d],c);c()}else{e=u("lxm_sl_trigger",a.a);for(g=e.length;g--;)s(e[g],"click",hc(a));if(T(c.lxm_static))for(a.I=!0,c=u("lxm_banner_sc",a.a),e=c.length;e--;)s(c[e],
"click",ic());else{b&&("android"==N()&&4<=S()||(a.a.style.position=Na,a.a.style.bottom="auto"),a.U=T(c.initheight),a.V=Ha(a.a,"lxm_bottom"),a.B=Ha(a.a,"lxm_tizer")?u("lxm_tizer_img",a.a)[0]:!1,a.W=u("lxm_js_fontsize",a.a),a.Y=u("lxm_js_lineheight",a.a),a.Z=u("lxm_js_lineheightpx",a.a),a.X=u("lxm_js_height",a.a));if(!pb){if("android"==N()&&3>S())d=t("meta"),d.name="viewport",d.content="width=device-width",n.head.appendChild(d);else for(d in e=["orientationchange","touchmove","touchend","scroll","resize"],
e)e.hasOwnProperty(d)&&s(f,e[d],Fb);pb=!0}l(a.refresh)&&a.refresh&&(a.c&&clearTimeout(a.c),a.c=setTimeout(jc(a),1E3*a.refresh));Fb()}}},Fb=function(){Qa&&clearTimeout(Qa);Qa=setTimeout(function(){Gb(!0)},250)},Gb=function(a){if(!Sa){var b=0;Sa=!0;Pa++;for(var c in y)if(y.hasOwnProperty(c)){var d=y[c];if(!d.I&&!d.v&&!d.j){var e=d.a,g=Hb(),k=kc(),h=[f.pageXOffset,f.pageYOffset],l=[f.pageXOffset,f.pageYOffset+f.innerHeight];e.style.width=h[0]+f.innerWidth-h[0]+p;"android"==N()&&4<=S()||(e.style.left=
h[0]+p,e.style.top=d.V?l[1]-e.offsetHeight+p:h[1]+p);O()?v(e,"lxm_landscape"):$(e,"lxm_landscape");g=fa(d.U/g);e.style.height=g+p;la(d.X,"height",g+p);la(d.Z,"lineHeight",g+p);d.B&&(e=bb(g*(J()?0.8:0.95))+p,d.B.style.height=e,d.B.style.width=e);e=J()?100:50>k?80:100;la(d.W,"fontSize",k+"%");la(d.Y,"lineHeight",e+"%");b++}}b&&a&&(Ra&&clearTimeout(Ra),Ra=setTimeout(function(){Gb(!1)},250));Sa=!1}},S=function(){if(!1===Aa){var a=N();Aa=0;"android"==a&&(Aa=ea(M.slice(M.indexOf("android")+8)))}return Aa},
N=function(){if(!za){za="unknown";for(var a=[["android","android"],["ipad","ios"],["iphone","ios"],["ipod","ios"]],b=0;b<a.length;b++)if(~M.indexOf(a[b][0])){za=a[b][1];break}}return za},O=function(){var a=N(),b=0===window.orientation||180===window.orientation;return R&&"android"==a&&4<=S()?!b:R&&"android"==a?b:!b},Hb=function(){if(qb!=Pa){var a=N(),b=1,c=J()?1:window.devicePixelRatio;"ios"==a&&~M.indexOf("iphone")&&!J()&&(c=2);b=n.documentElement.clientWidth/f.innerWidth/c;if(~M.indexOf("ipad")||
"android"==a&&R&&1<c)b*=c;O()&&"android"==a&&!J()?b*=2:O()&&"android"==a&&J()&&(b*=0.85);!O()&&R&&"android"==a?b/=(S(),1.5):O()&&R&&"android"==a&&!J()&&(b/=4<=S()?1.75:1.5);rb=z(100*b)/100;qb=Pa}return rb},kc=function(){var a=N(),b=Hb(),c=1,c=J()?1/b:(1.144>b?1:2.75<b?1.26:4.431914*Math.pow(b,8)-65.6671503*Math.pow(b,7)+417.3583138*Math.pow(b,6)-1484.928018*Math.pow(b,5)+3233.105604*Math.pow(b,4)-4410.2163548*Math.pow(b,3)+3680.9724495*Math.pow(b,2)-1719.2504263*b+345.6426082)/b;"android"==a&&3>S&&
!O()?c=1.3*b:O()&&(c*=1.15);return c=z(100*c)},J=function(){if(-1===Ba){Ba=!1;for(var a=Z("meta",!0),b=a.length;b--;)if(l(a[b].content)){var c=a[b].content;if(~c.indexOf("width=device-width")||~c.indexOf("initial-scale=1")||~c.indexOf("user-scalable=no")){Ba=!0;break}}}return Ba},Eb=function(a){for(var b=!1,c=Z("meta",!0),d=c.length;d--;)if(l(c[d].name)&&"viewport"==c[d].name){var e=c[d].content;if(~e.indexOf(a)&&(e=RegExp(a+" *?= *?(.+?)(?:[, ]|$)","m").exec(e),null!=e)){b=e[1];break}}return b},
Db=function(a,b,c){!1!==c&&v(a,"lxm_"+b+"_"+(0.5*Math.ceil(parseFloat(c)/0.5)).toString().replace(".","_"))},dc=function(a){return function(b){if(b||f.event)b=b||f.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;a.a.style.display="none";a.j=!0;a.v&&(b=Cb(),Ya?Ea(b,"content",Ya):b.parentNode.removeChild(b));if(T(a.closeTimeout)&&(b=T(a.closeTimeout))){var c=new Date;c.setTime(c.getTime()+6E4*b);C.set("_lxblockignore_"+a.l,1,c,"/")}return!0}},hc=function(a){return function(b){if(b||f.event)b=
b||f.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;u("lxm_sl",a.a)[0].style.display="";return!1}},ec=function(a,b){return function(c){if(c||f.event)c=c||f.event,c.stopPropagation?c.stopPropagation():c.cancelBubble=!0,c.preventDefault&&c.preventDefault();c=u("lxm_sl",a.a)[0];c.style.display="";c=u("lxm_button",c)[0];c.href=b.href;c.title=b.title;return!1}},ic=function(){return function(a){a.stopPropagation();var b=h(this.style.right);return h(a.pageX)-h(this.offsetLeft)<this.getAttribute("triggerWidth")?
(b!=this.getAttribute("baseStyleRight")&&0!=b||Ib(this,0==b?-1:1),a.preventDefault(),!1):!0}},fc=function(a){return function(b){b.stopPropagation();var c=u("lx_links_position",a.a)[0];Ha(c,"anishow")?(v(c,"anihide"),$(c,"anishow")):(v(c,"anishow"),$(c,"anihide"));b.preventDefault();return!1}},gc=function(a){return function(){O()?v(a.a,"lxm_landscape"):$(a.a,"lxm_landscape");n.getElementById("lx_dbg_fullscreen")&&(n.getElementById("lx_dbg_fullscreen").innerHTML=a.a.className);return!1}},Ib=function(a,
b){setTimeout(function(){var c=parseInt(a.style.right);0<b&&0==c||0>b&&c==Da(a)||(c+=6*b,0<c&&(c=0),c<Da(a)&&(c=Da(a)),a.style.right=c+"px",Ib(a,b))},10)},jc=function(a){return function(){if(a.e)return!1;a.c&&clearTimeout(a.c);a.e=!0;E(H+ca+a.l+"/"+ma(),B())}};if(!w)var xb=function(a){var b=new Date,c=b.getTime();b.setTime(c+2592E6);C.set(Ua,a,b,"/");C.set(sb,C.get(tb,0),b,"/");C.set(tb,c,b,"/")};if(!w)var Jb=!1,Y=[],K=[],da=[],Zb=function(a,b){if(!Jb){Jb=!0;var c=t("link");c.setAttribute("rel","stylesheet");
c.setAttribute(Fa,"text/css");c.href=H+"s.luxadv.com//images/i/video26/videostyle.css";ja.appendChild(c)}var d={b:ga(),f:!1};K[d.b]=Y[d.b]=da[d.b]=!1;d.d=b;d.t=!1;c=t("div");c.style.cssText=b.Q;c.style.width=b.q+p;c.style.height=0+p;c.style.margin="0 auto";c.style.textAlign="center";c.style.display="block";c.style.overflow="hidden";c.style.opacity=0;c.style.position="relative";v(c,"lx_amn_inlvid");var e=t("a");e.href="javascript:void(0);";v(e,"ico");e.appendChild(t("span"));var g=t("a");g.href=
b.D;g.target="_blank";v(g,"vid");var k=t("video");k.width=b.q;k.height=bb(b.q/(b.ea/b.ba));k.controls=!1;k.autoplay=!1;k.volume=0;var h=t("source");h.src=b.da;k.appendChild(h);d.a=k;d.h=c;d.href=g;d.u=e;d.nextSibling=a.nextSibling;d.previousSibling=a;h=t("a");h.href="javascript:void(0);";h.innerHTML="\u0417\u0430\u043a\u0440\u044b\u0442\u044c";s(h,"click",function(){return function(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;Kb(d);return!1}}());v(h,"cls");d.r=h;b.S&&(h.style.display=
"none");var l=t("a");l.href="javascript:void(0);";l.innerHTML='<span class="bg_lnk"></span><span class="txt_lnk">\u0420\u0435\u043a\u043b\u0430\u043c\u0430</span>';v(l,"adv");d.p=l;b.T&&(l.style.display="none");var m=t("a");m.href="javascript:void(0);";m.innerHTML='<span class="bg_lnk"></span><span class="txt_lnk">'+d.d.J+"</span>";v(m,"adv_txt");d.o=m;d.d.J||(m.style.display="none");var n=t("div");v(n,"dsc");n.innerHTML='<span><a href="http://video.adlabsnetworks.com/?utm_source=partners&utm_medium=logo" target="_blank">Powered by</a></span>';
var q=t("a");q.href=b.D;q.target="_blank";n.appendChild(q);q.innerHTML="\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u043d\u0430 \u0441\u0430\u0439\u0442 \u0440\u0435\u043a\u043b\u0430\u043c\u043e\u0434\u0430\u0442\u0435\u043b\u044f";s(k,"play pause ended timeupdate",function(){return function(a){lc(d,a)}}());s(k,"mouseover",function(){return function(){mc(d)}}());s(k,"mouseout",function(){return function(){nc(d)}}());s(g,"click",function(){return function(){d.a.pause();return!0}}());d.O=function(){return function(){Za(d)}}();
s(f,"focus scroll",d.O);g.appendChild(k);c.appendChild(h);c.appendChild(l);c.appendChild(m);c.appendChild(e);c.appendChild(g);c.appendChild(n);a.parentNode.insertBefore(c,a.nextSibling);Y[d.b]=setTimeout(function(){Za(d)},50)},$a=function(a,b,c){da[a.b]&&clearTimeout(da[a.b]);var d=G(a.h),e=h(d.height),g=a.d.G?0:120;1==b&&e<a.a.height||-1==b&&e>g?(a.h.style.height=e+5*b+p,1==b?a.h.style.opacity=parseFloat(d.opacity)+z(1/(a.a.height/5),3)*b:(d=G(a.href),a.href.style.opacity=parseFloat(d.opacity)+z(1/
((a.a.height-g)/5),3)*b,a.u.style.opacity=a.href.style.opacity,a.r.style.opacity=a.href.style.opacity,a.p.style.opacity=a.href.style.opacity,a.o.style.opacity=a.href.style.opacity),da[a.b]=setTimeout(function(){$a(a,b,c)},10)):(1==b?(a.f=1==b,a.h.style.opacity=h(a.f)):-1==b&&0==g&&(a.h.style.display="none"),c())},Za=function(a){Y[a.b]&&clearTimeout(Y[a.b]);Y[a.b]=setTimeout(function(){oc(a)},50)},oc=function(a){if(!a.f){for(var b=!1,c=Ma(),d=a.a.getClientRects(),e=0,g=d.length;e<g;e++){var f=d[e];
if(0<=f.top&&f.top<c){b=!0;break}}b&&$a(a,1,function(){return function(){Za(a)}}())}a.f&&a.a.duration!=a.a.currentTime&&((b=ub(a.a))&&a.a.paused?a.a.play():b||a.a.pause())},lc=function(a,b){var c=b.type;if("pause"!=c||a.a.duration!=a.a.currentTime)"play"==c&&0==a.a.currentTime&&(c="started"),"timeupdate"==c&&100!=a.d.F&&!a.t&&a.a.duration*a.d.F/100<=a.a.currentTime&&(a.t=!0,setTimeout(function(){E(a.d.N,B())},0)),"started"==c&&setTimeout(function(){E(a.d.ca,B())},0),"ended"==c&&(a.t||setTimeout(function(){E(a.d.N,
B())},0),Kb(a))},Kb=function(a){$a(a,-1,function(){return function(){Ga(f,"focus scroll",a.O);delete K[a.b];delete Y[a.b];delete da[a.b];a.d.G?a.h.parentNode.removeChild(a.h):(a.href.parentNode.removeChild(a.href),a.u.parentNode.removeChild(a.u),a.r.parentNode.removeChild(a.r),a.p.parentNode.removeChild(a.p),a.o.parentNode.removeChild(a.o))}}())},mc=function(a){K[a.b]&&clearTimeout(K[a.b]);K[a.b]=setTimeout(function(){1>a.a.volume&&ab(a,1,1)},100)},nc=function(a){K[a.b]&&clearTimeout(K[a.b]);K[a.b]=
setTimeout(function(){0<a.a.volume&&ab(a,0,-1)},100)},ab=function(a,b,c){0.1<(b-a.a.volume)*c?(a.a.volume=z(a.a.volume+0.1*c,2),K[a.b]=setTimeout(function(){ab(a,b,c)},25)):a.a.volume=b};w||xb(h(C.get(Ua,0))+1);(function(){for(var a in m)if(m.hasOwnProperty(a)&&"object"==typeof m[a]){var b=n.getElementById(m[a].id),c=!1;l(m[a].type)&&"float"==m[a].type&&C.s("_lxretpopupignore")&&(c=!0);l(m[a].type)&&("inlinevideo"==m[a].type||"js_npm"==m[a].type&&D(m[a].check))&&(null!==n.querySelector(m[a].check)?
b=!0:c=!0);if(l(m[a].debug))if(n.location.search){var d;d=n.location.search;d=d.split("+").join(" ");for(var e={},g=void 0,h=/[?&]?([^=]+)=([^&]*)/g;g=h.exec(d);)e[decodeURIComponent(g[1])]=decodeURIComponent(g[2]);d=e;l(d.lx_debugmode)&&1==d.lx_debugmode||(c=!0)}else c=!0;T(m[a].closeTimeout)&&C.s("_lxblockignore"+a)&&(c=!0);!b||c?delete m[a]:pa+=1}if(pa)for(var p in m)m.hasOwnProperty(p)&&"object"==typeof m[p]&&(p in f[q].blocks?delete m[p]:f[q].blocks[p]=Wa)})();La(0)})();
